name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: make build

    - name: Install
      run: sudo make install

    - name: Uninstall
      run: sudo make uninstall
