name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Build
      run: make build/libzarg.so

    - name: Install
      run: sudo make install

    - name: Test
      run: |
        cd ./test
        make ../build/test
        ./automated.sh

    - name: Uninstall
      run: sudo make uninstall
